### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by turgro** [ursweiss/7-Segment-LED-Clock#3]
Hi,

I've tried to compile on IDE 2.3.2 with libraries that you specify but I've got error:

```
In file included from c:\Users\...\Documents\Arduino\libraries\ESPAsync_WiFiManager\src/ESPAsync_WiFiManager.h:41,
                 from C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h:210,
                 from C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\7-Segment-LED-Clock.ino:29:
c:\Users\...\Documents\Arduino\libraries\ESPAsync_WiFiManager\src/ESPAsync_WiFiManager.hpp:222:10: fatal error: ESPAsyncDNSServer.h: No such file or directory
  222 | #include <ESPAsyncDNSServer.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
```

So, I manually install _[ESP_AsynsDNSServer](https://github.com/devyte/ESPAsyncDNSServer)_, I've got other error
And if I comment this include from line 222 in file mention above, I've got the same error as below

```
In file included from c:\Users\...\Documents\Arduino\libraries\FastLED\src/FastLED.h:67,
                 from C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\7-Segment-LED-Clock.ino:24:
c:\Users\...\Documents\Arduino\libraries\FastLED\src/fastspi.h:145:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  145 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h:148,
                 from C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\7-Segment-LED-Clock.ino:29:
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h: In constructor 'DoubleResetDetector::DoubleResetDetector(int, int)':
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:120:29: error: 'LittleFS' was not declared in this scope
  120 |       #define FileFS        LittleFS
      |                             ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:175:12: note: in expansion of macro 'FileFS'
  175 |       if (!FileFS.begin())
      |            ^~~~~~
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h: In member function 'bool DoubleResetDetector::detectRecentlyResetFlag()':
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:120:29: error: 'LittleFS' was not declared in this scope
  120 |       #define FileFS        LittleFS
      |                             ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:268:11: note: in expansion of macro 'FileFS'
  268 |       if (FileFS.exists(DRD_FILENAME))
      |           ^~~~~~
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h: In member function 'void DoubleResetDetector::setRecentlyResetFlag()':
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:120:29: error: 'LittleFS' was not declared in this scope
  120 |       #define FileFS        LittleFS
      |                             ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:324:19: note: in expansion of macro 'FileFS'
  324 |       File file = FileFS.open(DRD_FILENAME, "w");
      |                   ^~~~~~
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h: In member function 'void DoubleResetDetector::clearRecentlyResetFlag()':
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:120:29: error: 'LittleFS' was not declared in this scope
  120 |       #define FileFS        LittleFS
      |                             ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:370:19: note: in expansion of macro 'FileFS'
  370 |       File file = FileFS.open(DRD_FILENAME, "w");
      |                   ^~~~~~
In file included from c:\Users\...\Documents\Arduino\libraries\ESPAsync_WiFiManager\src/ESPAsync_WiFiManager.h:42,
                 from C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h:210:
c:\Users\...\Documents\Arduino\libraries\ESPAsync_WiFiManager\src/ESPAsync_WiFiManager-Impl.h: In member function 'void ESPAsync_WiFiManager::setupConfigPortal()':
c:\Users\...\Documents\Arduino\libraries\ESPAsync_WiFiManager\src/ESPAsync_WiFiManager-Impl.h:355:12: error: 'class WiFiClass' has no member named 'getAutoConnect'; did you mean 'getAutoReconnect'?
  355 |   if (WiFi.getAutoConnect() == 0)
      |            ^~~~~~~~~~~~~~
      |            getAutoReconnect
c:\Users\...\Documents\Arduino\libraries\ESPAsync_WiFiManager\src/ESPAsync_WiFiManager-Impl.h:356:10: error: 'class WiFiClass' has no member named 'setAutoConnect'; did you mean 'setAutoReconnect'?
  356 |     WiFi.setAutoConnect(1);
      |          ^~~~~~~~~~~~~~
      |          setAutoReconnect
C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h: In function 'bool loadConfigData()':
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:120:29: error: 'LittleFS' was not declared in this scope
  120 |       #define FileFS        LittleFS
      |                             ^~~~~~~~
C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h:421:15: note: in expansion of macro 'FileFS'
  421 |   File file = FileFS.open(CONFIG_FILENAME, "r");
      |               ^~~~~~
C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h: In function 'void saveConfigData()':
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:120:29: error: 'LittleFS' was not declared in this scope
  120 |       #define FileFS        LittleFS
      |                             ^~~~~~~~
C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h:452:15: note: in expansion of macro 'FileFS'
  452 |   File file = FileFS.open(CONFIG_FILENAME, "w");
      |               ^~~~~~
C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h: In function 'void initEspAsyncWiFiManager()':
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:120:29: error: 'LittleFS' was not declared in this scope
  120 |       #define FileFS        LittleFS
      |                             ^~~~~~~~
C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h:489:5: note: in expansion of macro 'FileFS'
  489 |     FileFS.format();
      |     ^~~~~~
c:\Users\...\Documents\Arduino\libraries\ESP_DoubleResetDetector\src/ESP_DoubleResetDetector.h:120:29: error: 'LittleFS' was not declared in this scope
  120 |       #define FileFS        LittleFS
      |                             ^~~~~~~~
C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h:492:8: note: in expansion of macro 'FileFS'
  492 |   if (!FileFS.begin(true)) {
      |        ^~~~~~
C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h:530:3: error: 'DNSServer' was not declared in this scope; did you mean 'webServer'?
  530 |   DNSServer dnsServer;
      |   ^~~~~~~~~
      |   webServer
C:\Users\...\Downloads\STL\Zegarek ESP - LED\7-Segment-LED-Clock-main-Printables-68013\7-Segment-LED-Clock\ESPAsync_WiFiManager_DRD.h:532:58: error: 'dnsServer' was not declared in this scope; did you mean 'webServer'?
  532 |   ESPAsync_WiFiManager ESPAsync_wifiManager(&webServer, &dnsServer, "AsyncConfigOnDoubleReset");
      |                                                          ^~~~~~~~~
      |                                                          webServer
Multiple libraries were found for "WiFiClient.h"
  Used: C:\Users\...\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.2.0\libraries\WiFi
  Not used: C:\Users\...\Documents\Arduino\libraries\WiFi101
exit status 1

Compilation error: 'DNSServer' was not declared in this scope; did you mean 'webServer'?
````

And Stuck.
I tryed many programs to run my new clock based on ESP8266 or ESP32 but ever of them is old and not working :(

Update a few hours later.
With help Chat GPT I was manage to correct DNS Server by changing in file `ESPAsync_WiFiManager_DRD.h`
`DNSServer dnsServer;`
to
`AsyncDNSServer dnsServer;`

And this worked.
Other thing that GPT helped was in file `ESPAsync_WiFiManager-Impl.h` changing `WiFi.getAutoConnect()` and `WiFi.setAutoConnect()` to `WiFi.getAutoReconnect()` and `WiFi.setAutoReconnect()`

Also I removed WiFi101 from libraries folder, and this works, but still have errors _LittleFS_

I've tried on IDE 1.8.18 and got the same result.

Help

**Comment by turgro** [comment]
Another update:

Ok. `#include <LittleFS.h>` was in project but not at begining, I add it on the top and compiling goes thru.
Next problem I just copy from Chat GPT, because it worked:

"
Ah, looks like you're almost there, but there's a small issue with the capitalization of `LITTLEFS`. It seems that in the `ESPAsync_WiFiManager_DRD.h` file, it's trying to use `LITTLEFS` in uppercase, but in ESP32, it’s actually `LittleFS` with a capital "L" and lowercase "fs".

Solution: Fix the `LITTLEFS` Typo
In the `ESPAsync_WiFiManager_DRD.h` file, find this line:

`FS* filesystem = &LITTLEFS;`

And change it to:

`FS* filesystem = &LittleFS;`

Why?
In ESP32, the LittleFS object is defined in the library as `LittleFS`, not `LITTLEFS`. The compiler is case-sensitive, so it can't find `LITTLEFS` (which does not exist), but it can find `LittleFS`.
"

This worked, and compiler is going and going and stuck. After reset IDE, compiler to his job but there's other errors.

At the end there is warning about not defining SPI pins, and for me (i'm noob), Chat GPT explanation is sufficient:

"it's just a message that the FastLED library is giving you. It means that FastLED is not using hardware SPI for controlling your LEDs but instead is using software (bit-banging). This is usually fine unless you're running a lot of LEDs or need the performance boost of hardware SPI. (...) If you're fine with bit-banging (which is usually acceptable for small setups), then the warning can simply be ignored. The library will still work, but it will use the software SPI method, which can be slower for larger LED arrays"


ERRORS:


```
c:\Users\...\Documents\Arduino\libraries\FastLED\src\noise.cpp: In function 'void fill_raw_2dnoise8(uint8_t*, int, int, uint8_t, q44, fract8, int, uint16_t, int, uint16_t, int, uint16_t)':
c:\Users\...\Documents\Arduino\libraries\FastLED\src\noise.cpp:596:100: error: ambiguous overload for 'operator*' (operand types are 'q44' {aka 'q<unsigned char, 4, 4>'} and 'int')
  596 |     fill_raw_2dnoise8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, freq44 * scalex, y*freq44, freq44 * scaley, time);
      |                                                                                             ~~~~~~ ^ ~~~~~~
      |                                                                                             |        |
      |                                                                                             |        int
      |                                                                                             q44 {aka q<unsigned char, 4, 4>}
In file included from c:\Users\...\Documents\Arduino\libraries\FastLED\src\pixeltypes.h:7,
                 from c:\Users\...\Documents\Arduino\libraries\FastLED\src\controller.h:9,
                 from c:\Users\...\Documents\Arduino\libraries\FastLED\src\FastLED.h:49,
                 from c:\Users\...\Documents\Arduino\libraries\FastLED\src\noise.cpp:2:
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:833:14: note: candidate: 'uint32_t q<T, F, I>::operator*(uint32_t) [with T = unsigned char; int F = 4; int I = 4; uint32_t = long unsigned int]'
  833 |     uint32_t operator*(uint32_t v) { return (v*i) + ((v*f)>>F); }
      |              ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:834:14: note: candidate: 'uint16_t q<T, F, I>::operator*(uint16_t) [with T = unsigned char; int F = 4; int I = 4; uint16_t = short unsigned int]'
  834 |     uint16_t operator*(uint16_t v) { return (v*i) + ((v*f)>>F); }
      |              ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:835:13: note: candidate: 'int32_t q<T, F, I>::operator*(int32_t) [with T = unsigned char; int F = 4; int I = 4; int32_t = long int]'
  835 |     int32_t operator*(int32_t v) { return (v*i) + ((v*f)>>F); }
      |             ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:836:13: note: candidate: 'int16_t q<T, F, I>::operator*(int16_t) [with T = unsigned char; int F = 4; int I = 4; int16_t = short int]'
  836 |     int16_t operator*(int16_t v) { return (v*i) + ((v*f)>>F); }
      |             ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\noise.cpp:596:127: error: ambiguous overload for 'operator*' (operand types are 'q44' {aka 'q<unsigned char, 4, 4>'} and 'int')
  596 |     fill_raw_2dnoise8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, freq44 * scalex, y*freq44, freq44 * scaley, time);
      |                                                                                                                        ~~~~~~ ^ ~~~~~~
      |                                                                                                                        |        |
      |                                                                                                                        |        int
      |                                                                                                                        q44 {aka q<unsigned char, 4, 4>}
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:833:14: note: candidate: 'uint32_t q<T, F, I>::operator*(uint32_t) [with T = unsigned char; int F = 4; int I = 4; uint32_t = long unsigned int]'
  833 |     uint32_t operator*(uint32_t v) { return (v*i) + ((v*f)>>F); }
      |              ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:834:14: note: candidate: 'uint16_t q<T, F, I>::operator*(uint16_t) [with T = unsigned char; int F = 4; int I = 4; uint16_t = short unsigned int]'
  834 |     uint16_t operator*(uint16_t v) { return (v*i) + ((v*f)>>F); }
      |              ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:835:13: note: candidate: 'int32_t q<T, F, I>::operator*(int32_t) [with T = unsigned char; int F = 4; int I = 4; int32_t = long int]'
  835 |     int32_t operator*(int32_t v) { return (v*i) + ((v*f)>>F); }
      |             ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:836:13: note: candidate: 'int16_t q<T, F, I>::operator*(int16_t) [with T = unsigned char; int F = 4; int I = 4; int16_t = short int]'
  836 |     int16_t operator*(int16_t v) { return (v*i) + ((v*f)>>F); }
      |             ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\noise.cpp: In function 'void fill_raw_2dnoise16(uint16_t*, int, int, uint8_t, q88, fract16, int, uint32_t, int, uint32_t, int, uint32_t)':
c:\Users\...\Documents\Arduino\libraries\FastLED\src\noise.cpp:634:101: error: ambiguous overload for 'operator*' (operand types are 'int' and 'q88' {aka 'q<short unsigned int, 8, 8>'})
  634 |     fill_raw_2dnoise16(pData, width, height, octaves-1, freq88, amplitude, skip, x *freq88 , scalex *freq88, y * freq88, scaley * freq88, time);
      |                                                                                              ~~~~~~ ^~~~~~~
      |                                                                                              |       |
      |                                                                                              int     q88 {aka q<short unsigned int, 8, 8>}
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:842:49: note: candidate: 'uint32_t operator*(uint32_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; uint32_t = long unsigned int]'
  842 | template<class T, int F, int I> static uint32_t operator*(uint32_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:843:49: note: candidate: 'uint16_t operator*(uint16_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; uint16_t = short unsigned int]'
  843 | template<class T, int F, int I> static uint16_t operator*(uint16_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:844:48: note: candidate: 'int32_t operator*(int32_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; int32_t = long int]'
  844 | template<class T, int F, int I> static int32_t operator*(int32_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:845:48: note: candidate: 'int16_t operator*(int16_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; int16_t = short int]'
  845 | template<class T, int F, int I> static int16_t operator*(int16_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\noise.cpp:634:129: error: ambiguous overload for 'operator*' (operand types are 'int' and 'q88' {aka 'q<short unsigned int, 8, 8>'})
  634 |     fill_raw_2dnoise16(pData, width, height, octaves-1, freq88, amplitude, skip, x *freq88 , scalex *freq88, y * freq88, scaley * freq88, time);
      |                                                                                                                          ~~~~~~ ^ ~~~~~~
      |                                                                                                                          |        |
      |                                                                                                                          int      q88 {aka q<short unsigned int, 8, 8>}
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:842:49: note: candidate: 'uint32_t operator*(uint32_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; uint32_t = long unsigned int]'
  842 | template<class T, int F, int I> static uint32_t operator*(uint32_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:843:49: note: candidate: 'uint16_t operator*(uint16_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; uint16_t = short unsigned int]'
  843 | template<class T, int F, int I> static uint16_t operator*(uint16_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:844:48: note: candidate: 'int32_t operator*(int32_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; int32_t = long int]'
  844 | template<class T, int F, int I> static int32_t operator*(int32_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:845:48: note: candidate: 'int16_t operator*(int16_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; int16_t = short int]'
  845 | template<class T, int F, int I> static int16_t operator*(int16_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\noise.cpp: In function 'void fill_raw_2dnoise16into8(uint8_t*, int, int, uint8_t, q44, fract8, int, uint32_t, int, uint32_t, int, uint32_t)':
c:\Users\...\Documents\Arduino\libraries\FastLED\src\noise.cpp:668:106: error: ambiguous overload for 'operator*' (operand types are 'int' and 'q44' {aka 'q<unsigned char, 4, 4>'})
  668 |     fill_raw_2dnoise16into8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, scalex *freq44, y*freq44, scaley * freq44, time);
      |                                                                                                   ~~~~~~ ^~~~~~~
      |                                                                                                   |       |
      |                                                                                                   int     q44 {aka q<unsigned char, 4, 4>}
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:842:49: note: candidate: 'uint32_t operator*(uint32_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; uint32_t = long unsigned int]'
  842 | template<class T, int F, int I> static uint32_t operator*(uint32_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:843:49: note: candidate: 'uint16_t operator*(uint16_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; uint16_t = short unsigned int]'
  843 | template<class T, int F, int I> static uint16_t operator*(uint16_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:844:48: note: candidate: 'int32_t operator*(int32_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; int32_t = long int]'
  844 | template<class T, int F, int I> static int32_t operator*(int32_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:845:48: note: candidate: 'int16_t operator*(int16_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; int16_t = short int]'
  845 | template<class T, int F, int I> static int16_t operator*(int16_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\noise.cpp:668:132: error: ambiguous overload for 'operator*' (operand types are 'int' and 'q44' {aka 'q<unsigned char, 4, 4>'})
  668 |     fill_raw_2dnoise16into8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, scalex *freq44, y*freq44, scaley * freq44, time);
      |                                                                                                                             ~~~~~~ ^ ~~~~~~
      |                                                                                                                             |        |
      |                                                                                                                             int      q44 {aka q<unsigned char, 4, 4>}
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:842:49: note: candidate: 'uint32_t operator*(uint32_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; uint32_t = long unsigned int]'
  842 | template<class T, int F, int I> static uint32_t operator*(uint32_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:843:49: note: candidate: 'uint16_t operator*(uint16_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; uint16_t = short unsigned int]'
  843 | template<class T, int F, int I> static uint16_t operator*(uint16_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:844:48: note: candidate: 'int32_t operator*(int32_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; int32_t = long int]'
  844 | template<class T, int F, int I> static int32_t operator*(int32_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\lib8tion.h:845:48: note: candidate: 'int16_t operator*(int16_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; int16_t = short int]'
  845 | template<class T, int F, int I> static int16_t operator*(int16_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In member function 'void ESP32RMTController::startOnChannel(int)':
c:\Users\...\Documents\Arduino\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:265:29: error: 'RMTMEM' was not declared in this scope
  265 |         mRMT_mem_start = & (RMTMEM.chan[mRMT_channel].data32[0].val);
      |                             ^~~~~~
c:\Users\...\Documents\Arduino\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::doneOnChannel(rmt_channel_t, void*)':
c:\Users\...\Documents\Arduino\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:345:5: error: 'gpio_matrix_out' was not declared in this scope; did you mean 'gpio_iomux_out'?
  345 |     gpio_matrix_out(pController->mPin, 0x100, 0, 0);
      |     ^~~~~~~~~~~~~~~
      |     gpio_iomux_out

exit status 1

Compilation error: exit status 1
```

So, another day with Chat GPT, looking for solutions.

FastLED that i'm using was 3.5.0, after update to the latest version, and delete my backup files (compiler found it), IT WORKS.

```
Sketch uses 1184830 bytes (90%) of program storage space. Maximum is 1310720 bytes.
Global variables use 50552 bytes (15%) of dynamic memory, leaving 277128 bytes for local variables. Maximum is 327680 bytes.

```
I tryed it for [ESP32 DEVKITV1](https://www.aliexpress.com/item/4000152270368.html?spm=a2g0s.9042311.0.0.61af4c4dESOka0) selected board, but instead of this, in my stuff I have only ESP32 MINI MH-EL LIVE, so i found this board in menu and for this board, compiler i going thru.

The last step is to flash the board, but i have problem with my company laptop and probaly I have blocked COM ports, so, right now I can't flash and test - f..

At the end of my journey (I hope so), maybe somene it help solve their problems.

**Comment by turgro** [comment]
Ok, i found solution for COM ports, and already flashed the board and.... asjaskfhsdkjfhsdjk.....
More errors, but this time in serial monitor: i've get looped message:

```
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4660
load:0x40078000,len:15576
load:0x40080400,len:4
load:0x40080404,len:3152
entry 0x400805a0

assert failed: tcp_alloc /IDF/components/lwip/lwip/src/core/tcp.c:1854 (Required to lock TCPIP core functionality!)
```

in progress....

update after 1 hour of trying solve this.

ChatGPT suggest that `getWeather` can cause the problem and how it says "_Wrap your call to getWeather() in an xTaskCreate to ensure it runs in its own task_" but i'm noob in programming so it's too much for me so I comment whole `void getWeather()` section and after that, it's comipiling but serial monitor gave the same error.

I surrender. Maybe one day somone resolve this problem.

**Comment by ursweiss** [comment]
I abandoned the code for a long long time, I'm sorry.
The old code broke at one point in time and I tried to fix it already several times, but only had limited success.
I'm working on a complete refactoring of the code atm.
Some code will be released today, but it's still WIP and upcoming releases may will break things (hope it will not).
